version: '3.4'

services:
  basketservice:
    image: mudho/basketservice
    depends_on:
      - basket.data
      - rabbitmq
    build:
      context: .
      dockerfile: BasketService/Dockerfile

  manufacturerservice:
    image: mudho/manufacturerservice
    build:
      context: .
      dockerfile: ManufacturerService/Dockerfile


  orderservice:
    image: mudho/orderservice
    depends_on:      
      - rabbitmq
      - orderservicedb
    build:
      context: .
      dockerfile: OrderService/Dockerfile


  paymentmethodservice:
    image: mudho/paymentmethodservice
    depends_on:
      - paymentmethodservicedb
    build:
      context: .
      dockerfile: PaymentMethodService/Dockerfile


  productcategoryservice:
    image: mudho/productcategoryservice
    depends_on:
      - productcategoryservicedb
    build:
      context: .
      dockerfile: ProductCategoryService/Dockerfile


  productservice:
    image: mudho/productservice,
    depends_on:
      - productservicedb
    build:
      context: .
      dockerfile: ProductService/Dockerfile


  shipmentmethodservice:
    image: mudho/shipmentmethodservice
    depends_on:
      - shipmentmethodservicedb
    build:
      context: .
      dockerfile: ShipmentMethodService/Dockerfile

  paymentservice:
    image: mudho/paymentservice 
    depends_on:
      - paymentservicedb
    build:
      context: .
      dockerfile: PaymentService/Dockerfile

  shoppingcartapigateway:
    image: mudho/shoppingcartapigateway
    ports:
     - "9008:80"
    build:
      context: .
      dockerfile: ShoppingCartApiGateWay/Dockerfile

 

  nosql.data:
    image: mongo
    
  basket.data:
    image: redis   
    volumes:
      - basketdata:/data

  customerfavourites.data:
    image: redis   
    volumes:
      - customerfavouritesdata:/data
    
    
      
  rabbitmq:
    hostname: my-rabbit
    container_name: rabbit   
    image: rabbitmq:3-management    
    volumes:
      - messegingdata:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  signalrnotificationservice:
    image: mudho/signalrnotificationservice
    build:
      context: .
      dockerfile: SignalrNotificationService/Dockerfile

 
  customerfavouritesservices:
    image: mudho/customerfavouritesservices
    build:
      context: .
      dockerfile: CustomerFavouritesServices/Dockerfile
    environment:
      "RedisHost": "customerfavourites.data"

  orderservicedb:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: CytonDb
       MYSQL_USER: emmanuel
       MYSQL_PASSWORD: ogoma@123
     volumes:
       - orderservicedata:/var/lib/mysql
     restart: always

  paymentmethodservicedb:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: CytonDb
       MYSQL_USER: emmanuel
       MYSQL_PASSWORD: ogoma@123
     volumes:
       - paymentmethodservicedata:/var/lib/mysql
     restart: always

  paymentservicedb:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: CytonDb
       MYSQL_USER: emmanuel
       MYSQL_PASSWORD: ogoma@123
     volumes:
       - paymentservicedata:/var/lib/mysql
     restart: always
  

  productservicedb:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: CytonDb
       MYSQL_USER: emmanuel
       MYSQL_PASSWORD: ogoma@123
     volumes:
       - productservicedata:/var/lib/mysql
     restart: always

  productcategoryservicedb:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: CytonDb
       MYSQL_USER: emmanuel
       MYSQL_PASSWORD: ogoma@123
     volumes:
       - productcategoryservicedata:/var/lib/mysql
     restart: always

  shipmentmethodservicedb:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: CytonDb
       MYSQL_USER: emmanuel
       MYSQL_PASSWORD: ogoma@123
     volumes:
       - shipmentmethodservicedata:/var/lib/mysql
     restart: always


  











volumes:
  basketdata:
  messegingdata:
  customerfavouritesdata:
  orderservicedata:
  paymentmethodservicedata:
  paymentservicedata:
  productservicedata:
  productcategoryservicedata:
  shipmentmethodservicedata:


    


  


 



