version: '3.4'

services:
  basketservice:
    image: mudho/basketservice
    depends_on:
      - basket.data
      - rabbitmq   

  manufacturerservice:
    image: mudho/manufacturerservice    


  orderservice:
    image: mudho/orderservice
    depends_on:      
      - rabbitmq   


  paymentmethodservice:
    image: mudho/paymentmethodservice  


  productcategoryservice:
    image: mudho/productcategoryservice
    

  productservice:
    image: mudho/productservice    


  shipmentmethodservice:
    image: mudho/shipmentmethodservice
    
  paymentservice:
    image: mudho/paymentservice
    depends_on:      
      - rabbitmq   

  shoppingcartapigateway:
    image: mudho/shoppingcartapigateway
    ports:
     - "80:80"    

 

  nosql.data:
    image: mongo
    
  basket.data:
    image: redis   
    volumes:
      - basketdata:/data
      
  rabbitmq:
    hostname: my-rabbit
    container_name: rabbit   
    image: rabbitmq:3-management    
    volumes:
      - messegingdata:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  basketdata:
  messegingdata:
    


  


 
