version: '3'

services:
  basketservice:
    image: basketservice
    build:
      context: .
      dockerfile: BasketService/Dockerfile

  manufacturerservice:
    image: manufacturerservice
    build:
      context: .
      dockerfile: ManufacturerService/Dockerfile


  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile


  paymentmethodservice:
    image: paymentmethodservice
    build:
      context: .
      dockerfile: PaymentMethodService/Dockerfile


  productcategoryservice:
    image: productcategoryservice
    build:
      context: .
      dockerfile: ProductCategoryService/Dockerfile


  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile


  shipmentmethodservice:
    image: shipmentmethodservice
    build:
      context: .
      dockerfile: ShipmentMethodService/Dockerfile


  shoppingcartapigateway:
    image: shoppingcartapigateway
    build:
      context: .
      dockerfile: ShoppingCartApiGateWay/Dockerfile

