version: '3'

services:
  basketservice:
    image: mudho/basketservice
    depends_on:
      - basket.data
      - rabbitmq
    build:
      context: .
      dockerfile: BasketService/Dockerfile

  manufacturerservice:
    image: mudho/manufacturerservice
    build:
      context: .
      dockerfile: ManufacturerService/Dockerfile


  orderservice:
    image: mudho/orderservice
    depends_on:      
      - rabbitmq
    build:
      context: .
      dockerfile: OrderService/Dockerfile


  paymentmethodservice:
    image: mudho/paymentmethodservice
    build:
      context: .
      dockerfile: PaymentMethodService/Dockerfile


  productcategoryservice:
    image: mudho/productcategoryservice
    build:
      context: .
      dockerfile: ProductCategoryService/Dockerfile


  productservice:
    image: mudho/productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile


  shipmentmethodservice:
    image: mudho/shipmentmethodservice
    build:
      context: .
      dockerfile: ShipmentMethodService/Dockerfile

  paymentservice:
    image: mudho/paymentservice
    depends_on:      
      - rabbitmq
    build:
      context: .
      dockerfile: PaymentService/Dockerfile

  shoppingcartapigateway:
    image: mudho/shoppingcartapigateway
    ports:
     - "9008:80"
    build:
      context: .
      dockerfile: ShoppingCartApiGateWay/Dockerfile

 

  nosql.data:
    image: mongo
    
  basket.data:
    image: redis   
    volumes:
      - basketdata:/data
      
  rabbitmq:
    hostname: my-rabbit
    container_name: rabbit   
    image: rabbitmq:3-management    
    volumes:
      - messegingdata:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  basketdata:
  messegingdata:
    


  


 
